apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "cachet.name" . }}
    chart: {{ template "cachet.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "cachet.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cachet.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cachet.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: cachethq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_KEY
              value: {{ .Values.appKey }}
{{ include "dbInfo" . | indent 12 }}
{{ include "emailInfo" . | indent 12 }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 25
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
